[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/check"
  to = "/.netlify/functions/check"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/check"
  status = 200
